# Generated by Django 6.0 on 2025-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="close_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата закрытия группы"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="draw_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата проведения жеребьевки"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="gift_distribution_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата расдачи подарков"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="gift_via_bot",
            field=models.BooleanField(default=False, verbose_name="Подарки через бота"),
        ),
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("drawn", "Жеребьевка проведена"),
                    ("distribution", "Расдача подарков"),
                    ("closed", "Закрыта"),
                ],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="gift_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Подарок (сообщение)"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="gift_sent",
            field=models.BooleanField(
                default=False, verbose_name="Подарок отправлен боту"
            ),
        ),
    ]
