# Generated by Django 6.0 on 2025-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_group_close_date_group_draw_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="gift_photo_file_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Подарок (фото file_id)",
            ),
        ),
    ]
